# /home/epic/docker-compose.yaml
version: "3.7"
services:

  epic-games-claimer:
    image: ech0sec/awesome-epic:daddy
    init: true
    command: [ "xvfb-run", "python3", "main.py", "claim" ]
    volumes:
      - "/home/epic/database/:/home/epic/database/"
      - "/home/epic/datas/:/home/epic/datas"
    environment:
      EPIC_EMAIL: # å¡«å…¥ä½ çš„è´¦å·ä¿¡æ¯
      EPIC_PASSWORD: # å¡«å…¥ä½ çš„è´¦å·ä¿¡æ¯
      PUSHER_TELEGRAM: # (optional) Apprise æ¶ˆæ¯æ¨é€ï¼Œä¸å¡«æˆ–å¡«é”™åˆ™ä¸å‘é€
      PLAYER: # (optional) æŒ‡å®šæ˜µç§°ï¼Œè¦†ç›–æ•æ„Ÿä¿¡æ¯ï¼Œä¸å¡«åˆ™ä½¿ç”¨å†…ç½®ç®—æ³•ç”Ÿæˆ
      GITHUB_REVERSE_PROXY: # (optional) åŠ é€Ÿå›½å†…æœåŠ¡å™¨æ‹‰å–æ¨¡å‹çš„é€Ÿåº¦ï¼Œå¡«å…¥ â€œdefaultâ€ ä½¿ç”¨é¡¹ç›®å†…ç½®çš„åå‘ä»£ç†

# ======================================
# [ğŸœ] é•œåƒç®€è¿°
# ======================================
# ech0sec/awesome-epic:daddy
# 1. å†…ç½® google-chrome ä»¥åŠ yolov5n6(onnx) model
# 2. ä»¥ä½ å–œæ¬¢çš„æ–¹å¼é…ç½®ç¯å¢ƒå˜é‡ï¼Œå¼€ç®±å³ç”¨
# 3. ä¿®æ”¹ command æœ«ä½å‚æ•°ï¼Œè°ƒç”¨ä¸åŒçš„è„šæ‰‹æ¶æŒ‡ä»¤

# ======================================
# [ğŸœ] è„šæ‰‹æ¶æŒ‡ä»¤é€Ÿè®°
# ======================================
# test      | [å‡çº§ä¸­]æ£€æµ‹æœåŠ¡å¿ƒè·³
# claim     | è®¤é¢†æ¸¸æˆå•†åŸå‘¨å…æ¸¸æˆåŠå…¶å…è´¹DLC
# unreal    | è®¤é¢†è™šå¹»å•†åŸæœˆå…å†…å®¹
# deploy    | éƒ¨ç½²ç³»ç»Ÿå®šæ—¶ä»»åŠ¡
# get       | æ¬ç©ºæ¸¸æˆå•†åŸçš„å…è´¹æ¸¸æˆæˆ–å…è´¹DLC

# ======================================
# [ğŸœ] ç›¸å…³æ–‡æ¡£
# ======================================
# docker-compose https://docs.docker.com/compose/reference/
# apprise https://github.com/caronc/apprise