name: scaffold_test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      EPÎ™C_EMAÎ™L: ${{ secrets.EPÎ™C_EMAÎ™L }}
      EPÎ™C_PASSWÎŸRD: ${{ secrets.EPÎ™C_PASSWÎŸRD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Scaffold Init
        run: |
          cd src && python main.py

      - name: Scaffold Install
        run: |
          cd src && python main.py install

      # ğŸ¦½å“Ÿï¼è¿™å¯ä¸å…´å«–å•Šå®å‹ï¼
      - name: Scaffold Test
        run: |
          cd src && python main.py test
